"""GitProvider interface."""

from typing import Protocol


class GitProvider(Protocol):
    def create_branch(self, name: str, from_ref: str = "main") -> dict: ...
    def create_pull_request(self, title: str, source: str, target: str, body: str = "") -> dict: ...
    def merge_pull_request(self, pr_id: str) -> dict: ...
    def get_status(self, pr_id: str) -> dict: ...
