from typing import Protocol


class TicketProvider(Protocol):
    def get_ticket(self, ticket_id: str) -> dict: ...
    def update_ticket(self, ticket_id: str, fields: dict) -> dict: ...
    def add_comment(self, ticket_id: str, comment: str) -> dict: ...
